-d /home/vagrant/workspace/verilogLeson/blink002/impl/synthesize/rev_1/blink002.vm
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cst /home/vagrant/workspace/verilogLeson/blink002/src/blink002.cst
-cfg /home/vagrant/workspace/verilogLeson/blink002/impl/pnr/device.cfg
-sdc /home/vagrant/workspace/verilogLeson/blink002/src/blink002.sdc
-bit
-tr
-ph
-timing
